# Generated by Django 5.0.1 on 2024-03-06 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='annotation',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates if the annotation has been validated'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='User who validated the annotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='is_confidential',
            field=models.BooleanField(default=False, verbose_name='Confidential Image'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='newapp.language'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('title', 'language')},
        ),
        migrations.CreateModel(
            name='ValidationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Assigned', max_length=50)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.annotation')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.image')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.language')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
