# Generated by Django 5.0.1 on 2024-03-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationtask',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Validated', 'Validated')], default='Assigned', max_length=50),
        ),
    ]
