# Generated by Django 5.0.1 on 2024-03-13 20:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_validationtask_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='validationtask',
            unique_together={('annotation', 'validator', 'status', 'assigned_by')},
        ),
    ]
