# Generated by Django 5.0.1 on 2024-04-01 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_validationtask_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_rating', models.IntegerField()),
                ('ui_feedback', models.TextField()),
                ('image_upload_rating', models.IntegerField(blank=True, null=True)),
                ('image_upload_feedback', models.TextField(blank=True, null=True)),
                ('annotation_process_rating', models.IntegerField()),
                ('annotation_process_feedback', models.TextField()),
                ('validation_process_rating', models.IntegerField(blank=True, null=True)),
                ('validation_process_feedback', models.TextField(blank=True, null=True)),
                ('overall_software_rating', models.IntegerField()),
                ('overall_feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
